UPDATE room SET bed_type = UPPER(bed_type);
UPDATE room SET room_type = UPPER(room_type);

ALTER TABLE room ALTER COLUMN amenities TYPE TEXT USING amenities::text;


ALTER TABLE CONTACT
    ADD COLUMN IF NOT EXISTS id_trip INT;

ALTER TABLE CONTACT
    ADD CONSTRAINT fk_contact_trip FOREIGN KEY (id_trip) REFERENCES TRIP(id) ON DELETE SET NULL;

ALTER TABLE IMAGE
    ADD COLUMN IF NOT EXISTS owner_id INT;

ALTER TABLE IMAGE
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE IMAGE
    ADD CONSTRAINT fk_image_owner FOREIGN KEY (owner_id) REFERENCES AppUser(id);
